# Generated by Django 5.1.15 on 2026-08-07 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='unidad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de departamento dentro de la torre. Solo aplica a propietarios.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='torre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Torre del condominio (1 a 25). Solo aplica a propietarios.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
