# Generated by Django 5.1.15 on 2026-08-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_remove_usuario_unidad_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('propietario', models.ForeignKey(limit_choices_to={'rol': 'propietario'}, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('numero', 'propietario')},
            },
        ),
    ]
