# Generated by Django 5.1.15 on 2026-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_estacionamiento'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='estacionamiento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'propietario')), fields=('torre', 'departamento'), name='unidad_unica_por_propietario'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'aprobado'])), fields=('patente',), name='patente_unica_activa'),
        ),
    ]
