# Generated by Django 6.1 on 2026-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0004_alter_usuario_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="fecha_fin",
            field=models.DateTimeField(blank=True),
        ),
    ]
