# Generated by Django 6.1 on 2026-08-10 23:42

import acceso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0007_visitante_token_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="patente",
            field=models.CharField(
                max_length=10, validators=[acceso.models.validar_patente]
            ),
        ),
    ]
