# Generated by Django 6.1 on 2026-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0008_alter_vehiculo_patente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="fecha_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
