# Generated by Django 6.1 on 2026-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0009_alter_visitante_fecha_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="numero_documento",
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
