# Generated by Django 6.1 on 2026-08-11 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0012_usuario_email_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estacionamiento",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "propietario"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estacionamientos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
